server:
  host: 116.204.9.108
  port: 12321

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/emoprobe?serverTimezone=GMT%2B8
    username: root
    password: 7bb5b2752c839ca1
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.minjer.mapper: DEBUG
