server:
  address: 127.0.0.1
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/emoprobe?serverTimezone=GMT%2B8
    username: root
    password: minjer
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.minjer.mapper: DEBUG